version: '3.9'

networks:
  ddos_network:
    driver: bridge

services:
  defender:
    image: ubuntu:latest
    container_name: defender
    ports:
      - "8080:80"
    networks:
      - ddos_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: >
      sh -c "DEBIAN_FRONTEND=noninteractive apt update &&
             DEBIAN_FRONTEND=noninteractive apt install -y nginx iptables -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold &&
             echo '<h1>Welcome to Defender</h1>' > /var/www/html/index.html &&
             nginx -t && nginx -g 'daemon off;'"

  attacker:
    image: python:3.10-slim
    container_name: attacker
    networks:
      - ddos_network
    volumes:
      - ./attacker:/scripts
    entrypoint: ["tail", "-f", "/dev/null"]